- name: Check ~/.bashrc.d
  stat: path="{{ config_home_user }}/.bashrc.d"
  register: bashrcdir

- name: Clone bashrc.d
  git:
    repo: "{{ config_repository }}/bashrc.d.git"
    dest: "{{ config_home_user }}/.bashrc.d"
    recursive: true
  when: not bashrcdir.stat.exists

- name: Load ~/.bashrc.d/* files from .bashrc
  blockinfile:
    dest: "{{ config_home_user }}/.bashrc"
    marker: '# {mark} PER-FILE CONFIGURATION'
    block: |
      if [ -d ~/.bashrc.d ]; then
        for b in ~/.bashrc.d/*.sh ; do
          source $b
        done
      fi
  when: not bashrcdir.stat.exists
