- name: Check if GNOME jasuarez theme exists
  ansible.builtin.stat:
    path: "{{ config_user_home }}/.themes/jasuarez"
  register: gnomethemedir

- name: Check if GNOME jasuarez theme is under version
  ansible.builtin.stat:
    path: "{{ config_user_home }}/.themes/jasuarez/.git"
  register: gnomethemegitdir
  when: gnomethemedir.stat.exists

- name: Clone/Update GNOME jasuarez theme
  ansible.builtin.git:
    repo: "{{ config_user_repos }}/gnome-theme"
    dest: "{{ config_user_home }}/.themes/jasuarez"
    version: "main"
    recursive: true
  when: not gnomethemedir.stat.exists or gnomethemegitdir.stat.exists
