- name: Check .gitconfig
  stat: path="{{ config_user_home }}/.gitconfig"
  register: gitconfig

- name: Check dotfiles
  stat: path="{{ config_dotfiles_dir }}/dotfiles"

- name: Clone dotfiles
  git:
    repo: https://github.com/jasuarez/dotfiles
    dest: "{{ config_dotfiles_dir }}/dotfiles"
    version: "main"
    recursive: no
  when: not gitconfig.stat.exists

- name: Link .gitconfig
  file:
    src: "{{ config_dotfiles_dir }}/dotfiles/gitconfig"
    dest: "{{ config_user_home }}/.gitconfig"
    state: link
  when: not gitconfig.stat.exists
