- name: Check ~/.emacs.d
  stat: path="{{ config_user_home }}/.emacs.d"
  register: emacsdir

- name: Clone emacs.d
  git:
    repo: "{{ config_user_repos }}/emacs.d.git"
    dest: "{{ config_user_home }}/.emacs.d"
    version: "main"
    recursive: true
  when: not emacsdir.stat.exists
