- name: Check ~/.emacs.d
  stat: path="{{ config_home_user }}/.emacs.d"
  register: emacsdir
  
- name: Clone emacs.d
  git:
    repo: "{{ config_repository }}/emacs.d.git"
    dest: "{{ config_home_user }}/.emacs.d"
    recursive: true
  when: not emacsdir.stat.exists

- name: Recompile emacs lisp files
  command: emacs -batch -eval '(byte-recompile-directory "{{ config_home_user }}/.emacs.d" 0)'
  ignore_errors: yes
  
- name: Install emacs plugins
  command: emacs -batch -u "{{ config_user }}" -f package-utils-upgrade-all
  ignore_errors: yes
