- name: Check ~/.emacs.d
  stat: path="{{ config_home_user }}/.emacs.d"
  register: emacsdir
  
- name: Clone emacs.d
  git:
    repo: "{{ config_repository }}/emacs.d.git"
    dest: "{{ config_home_user }}/.emacs.d"
    version: "main"
    recursive: true
  when: not emacsdir.stat.exists

