- name: Check .tmux.conf
  stat: path="{{ config_home_user }}/.tmux.conf"
  register: tmuxconf

- name: Check dotfiles
  stat: path="{{ config_dotfiles_dir }}/dotfiles"

- name: Clone dotfiles
  git:
    repo: https://github.com/jasuarez/dotfiles
    dest: "{{ config_dotfiles_dir }}/dotfiles"
    recursive: no
    version: "main"
  when: not tmuxconf.stat.exists

- name: Link .tmux.conf
  file:
    src: "{{ config_dotfiles_dir }}/dotfiles/tmux.conf"
    dest: "{{ config_home_user }}/.tmux.conf"
    state: link
  when: not tmuxconf.stat.exists
